### ISSUE TITLE
这是把llvm ir执行器搬到浏览器来了吗

### ISSUE THREAD

**Issue by uxctx** [qiaozi-tech/SecurityWorker#1]

**Comment by uxctx** [comment]
`  
function runMain() {
        createSecurityWorker('');
    }
`
`security_worker_new` 是Emscripten编译的函数了很难跟了，我估计只能跟着找到原始的IR字节，然后分析vm，序列化一个可视化语法出来，

我在想为什么不做webassembly 混淆，混淆webassembly 代码估计也有前途，甚至更快啊，

**Comment by ErosZy** [comment]
@lucpp wasm的执行必须依靠浏览器环境，同时wasm的规范是公开的，因此在还原时仍然可以拿到原始的wasm代码，再通过反向编译可以拿到类c代码。
SecurityWorker的目标是能够不写C++但是又有足够的安全强度，性能只是一方面。
