### ISSUE TITLE
questions about the library

### ISSUE THREAD

**Issue by pyu10055** [qiaozi-tech/SecurityWorker#3]
Hi

Thank you for sharing your work, couple questions, hope it is ok to ask here.

1. Seems the file size increases after encryption (100B -> 300B), is this a constant overhead or always 3 times the original size?
2. Is this a pure JS solution or it uses WASM?
3. How much works are left for supporting WeChat mini program?
4. The 官网 link is broken.

thanks

**Comment by ErosZy** [comment]
1. No. In fact, VM will account for about 180-230k. If your code has 40k, then the whole is about ~270k (or more, it depends on generated opcode size) .
2. It use WASM, we compiled an embedded JavaScript engine into WASM then port some WebWorker APIs.
3. The VM is still having some problems, including performance/code size/and available APIs. We should now replace the VM from Duktape to QuickJS, then provide more APIs, and then reduce the opcode instructions before going to support mini program.
4. Same as above, but you wanna try to use, i can give you a command line tool.
